package compiler

import (
	"monkey-lang/ast"
	"monkey-lang/code"
	"monkey-lang/object"
)

type Compiler struct {
	instructions code.Instructions // holds the generated bytecode
	constants    []object.Object   // constants pool
}

func New() *Compiler {
	return &Compiler{
		instructions: code.Instructions{},
		constants:    []object.Object{},
	}
}

func (c *Compiler) Compile(node ast.Node) error {
	return nil
}

func (c *Compiler) Bytecode() *Bytecode {
	return &Bytecode{
		Instructions: c.instructions,
		Constants:    c.constants,
	}
}

type Bytecode struct {
	Instructions code.Instructions // the instructions generated by Compiler
	Constants    []object.Object   // the constants evaluated by Compiler
}
